### ISSUE TITLE
Review Comp PR - Bigoli

### ISSUE THREAD

**Issue by chsahit** [RoboJackets/roboracing-software#111]
- [ ]        LICENSE
- [ ]        avc/launch/finish_detector.launch
- [ ]        avc/launch/mapper.launch
- [ ]        avc/launch/planner_avc.launch
- [ ]        avc/launch/start_detector.launch
- [ ]        avc/launch/test_start.launch
- [ ]        avc/package.xml
- [ ]        avc/src/color_detector_avc.cpp
- [ ]        avc/src/finish_detector/finish_detector.cpp
- [ ]        avc/src/finish_detector/finish_detector.h
- [ ]        avc/src/start_detector/start_detector.cpp
- [ ]        avc/src/start_detector/start_detector.h
- [ ]        iarrc/package.xml
- [ ]        rr_common/package.xml
- [ ]        rr_common/src/navigation_controller/navigation_controller.cpp
- [ ]        rr_common/src/planner/planner.cpp
- [ ]        rr_description/package.xml
- [ ]        rr_platform/launch/bigoli_drive_relay.launch
- [ ]        rr_platform/launch/bigoli_platform.launch
- [ ]        rr_platform/launch/logitech_camera.launch
- [ ]        rr_platform/launch/macaroni_platform.launch
- [ ]        rr_platform/launch/motor_relay.launch
- [ ]        rr_platform/launch/rosbag.launch
- [ ]        rr_platform/launch/wide_camera.launch
- [ ]        rr_platform/package.xml
- [ ]        rr_platform/src/bigoli_motor_relay_node/bigoli_drive_relay.cpp
- [ ]        rr_platform/src/bigoli_motor_relay_node/bigoli_steer_relay.cpp
- [ ]        sandbox/99-roboracing.rules
- [ ]        sandbox/package.xml

**Comment by jgkamat** [comment]
I think you want
`- []`
not
`[ ] -`

Markdown sucks.
