### ISSUE TITLE
Visualize /start_detected (rviz)

### ISSUE THREAD

**Issue by barulicm** [RoboJackets/roboracing-software#118]
Create an rviz panel that displays whether or not the car sees the start signal.

**Details**

1. Create a new rviz panel. See the Example Panel for details.
2. Subscribe to `/start_detected`
3. In the subscriber's callback, save the state of the detection as a member variable for your panel class.
4. Using your panel's `paintEvent()` method, render the current start signal state in a cool way (ie. a stoplight!)

Depends on #117

**Comment by Daniel-Martin576** [comment]
Updated issue created for this. #275
