### ISSUE TITLE
Visualize /chassis_state (rviz)

### ISSUE THREAD

**Issue by barulicm** [RoboJackets/roboracing-software#120]
Our motor relay nodes publish `rr_platform/chassis_state` messages on `/chassis_state`. This includes things like estop state, wheel speeds, etc. We'd like to visualize these in an rviz panel.

**Details**

1. Add a new rviz panel following the example panel in `rr_rviz_plugins`.
2. Make the new panel subscribe to `/chassis_state`
3. Render the data in the message in your panel. This might include a spedometer for speed, and color-coded indicators for estop and mux state.

**Comment by Daniel-Martin576** [comment]
Made new issue for this. #256
