### ISSUE TITLE
Implement Ultrasonic Sensor Array

### ISSUE THREAD

**Issue by btdubs** [RoboJackets/roboracing-software#127]
Firmware for microcontroller control of multiple ultrasonic sensors and a Ros node to output the obstacles detected as a point cloud. The point of this is to use the ultrasonic array to detect obstacles.

The firmware is found in the roboracing-firmware repo under[ macaroni_ultrasonic_array](https://github.com/RoboJackets/roboracing-firmware/tree/macaroni_ultrasonic_array) .
The ROS node is found under [ultrasonic_array](https://github.com/RoboJackets/roboracing-software/tree/ultrasonic_array)

**Comment by btdubs** [comment]
- [ ] Read CSV from serial

- [ ] Transform points using TF

- [ ] Combine multiple point clouds

- [ ] Publish point cloud

- [ ] Test with arduino

- [ ] Update arduino firmware to flipping sensor check to be slightly faster

- [ ] Update arduino firmware to Atmel chip from board we ordered

**Comment by ebretl** [comment]
@btdubs was this issue resolved?
