### ISSUE TITLE
Update Simulator Models

### ISSUE THREAD

**Issue by barulicm** [RoboJackets/roboracing-software#136]
- [ ] Sedani
- [x] EVGP stand-in bot

**Comment by barulicm** [comment]
Spent today fixing Bigoli's CAD so the steering assembly wasn't broken.
Still need to add sensors before I can export to Gazebo models.

**Comment by joshi1983** [comment]
What is EVGP Vehicle Simulator?  Is there a website or github project for it?  I'd like to learn more about it in case it gives me more ideas for IARRC Simulator( https://github.com/joshi1983/IARRCSim ).

**Comment by barulicm** [comment]
@joshi1983 EVGP Vehicle Simulator is just the name of a PR on this repository (#260). That PR, among other things, adds a model and other configuration files necessary to simulate the RoboJackets RoboRacing team's newest vehicle for a competition we are joining this year, the [evGrand Prix](https://evgrandprix.org/).

Our simulation tool still just uses [Gazebo](http://gazebosim.org/) with its native ROS integrations.
