### ISSUE TITLE
Encapsulate serial port code into a class

### ISSUE THREAD

**Issue by barulicm** [RoboJackets/roboracing-software#137]
Working on in [serial_library](https://github.com/RoboJackets/roboracing-software/tree/serial_library) branch. 
Using code based on [robojackets/stsl](https://github.com/RoboJackets/stsl)'s `SerialPort_LINUX`.

**Comment by barulicm** [comment]
Code changes complete. Needs to be tested on Macaroni.

**Comment by ebretl** [comment]
This worked well at competition, so I'm closing the issue
