### ISSUE TITLE
Python dependencies not included in package.xml

### ISSUE THREAD

**Issue by JasonGibson274** [RoboJackets/roboracing-software#143]
I know this is not on your master branch but I do not want to forget about this. You can add pip dependencies to your package.xml but your CI will fail if you do not install pip onto your docker image. This is in direct reference to keras and h5py

**Comment by chsahit** [comment]
Oooh, I'll add this in. Thanks for the catch. I'm planning to make a PR for the ml branch by the end of the week and I'll really appreciate if you can give it a look when that happens.
