### ISSUE TITLE
Test stoplight detection on new camera

### ISSUE THREAD

**Issue by ebretl** [RoboJackets/roboracing-software#146]
- [ ] test camera's view of bright stoplight
- [ ] if the red/green lights show up as pure white, adjust exposure/iris/gain as needed
- [ ] test stoplight_watcher (should publish true iff the light is green). Roughly characterize if and when it gives the wrong values
- [ ] record a bag file of the stoplight changing and upload to owncloud

**Comment by barulicm** [comment]
@ebretl Is this issue done now that we seem to think the stoplight code works?
