### ISSUE TITLE
Cleaner demonstration mode

### ISSUE THREAD

**Issue by ebretl** [RoboJackets/roboracing-software#208]
Last time we tested the demo mode (with work-in-progress reversing firmware), it oscillated back and forth quite a lot. Implement PID control with a target distance to fix this. In the process, fix some other things:
- rename avc_follower.launch to something demonstration-related and move it to rr_common
- use the closest point, not the average point

As of Feb 11, 2019: waiting on chassis speed measurement

**Comment by Daniel-Martin576** [comment]
Update issue #276  created for this
