### ISSUE TITLE
Global Center Line Finder

### ISSUE THREAD

**Issue by Daniel-Martin576** [RoboJackets/roboracing-software#273]
Find the centerline of the track after the cold lap. It should be a list of points that produce a closed circuit around the track through the middle of the lane. 

Steps:
- Find the distance of each cell to the closest wall
     - Convert to image and use OpenCV distance transform
     - Try to find something else online
     - Outside the track should be 0 and inside should be some positive x distance
- Use Uniform-cost Search to find loop around the course using the distance as a utility  
     - Set goal point behind you and add a wall between the start point and goal point to prevent the search from going backward
- Smooth the resultant circuit if needed 

Other Option (probably try this first):
- Just use navfn and global_planner packages and see how good a result you get

**Comment by Daniel-Martin576** [comment]
Maybe this is useful for the first part: https://github.com/artivis/distance_map

**Comment by btdubs** [comment]
General update on this since Daniel wasn't in the meeting today. We can now find the center line through the path, I am just debugging an issue where the final path is not outputting correctly in world coordinates (as compared to coordinates within the costmap).
