### ISSUE TITLE
Make Gazebo world with Closed EVGP track

### ISSUE THREAD

**Issue by Daniel-Martin576** [RoboJackets/roboracing-software#297]
Brian already made a .dae for this, so we just need to create the gazebo world and see how our car behaves without the map closer (hopefully faster and better).

**Comment by ebretl** [comment]
@dsiegler2000 should this still be open, given that we have merged #307 ?

**Comment by Daniel-Martin576** [comment]
This was originally for the closed version of the first track that Brian made which he put on my flash drive but it didn't seem complete and we have the real proposed one, so this issue can be closed in my opinion.
