### ISSUE TITLE
Add 3D Lidar

### ISSUE THREAD

**Issue by Daniel-Martin576** [RoboJackets/roboracing-software#299]
Since RR doesn't a 3D lidar yet, IGVC was kind enough to let us borrow their nice Velodyne one for our comp! It is way nicer to have a 3D lidar for obstacle detection, so update our lidar in the gazebo to match the specs of their lidar (you can look through their repo to see how they did it) ([urdf.xacro](https://github.com/RoboJackets/igvc-software/blob/master/igvc_description/urdf/jessii.urdf.xacro) and [urdf](https://github.com/RoboJackets/igvc-software/blob/master/igvc_description/urdf/jessi.urdf)). If you could give the option to switch between the two types (2D and 3D) it would be pretty nice too. 

Right now our stack uses the 2D lidar /scan to make a map, so if you are able to produce a 2D map of the world with 3D scan it would be ideal! You can either make your own node or maybe look into `octomap` and `pcl_ros`.

**Comment by JasonGibson274** [comment]
I would start by just using the horizontal beam. It would just be the same thing as you have now but with a longer range. 

You can talk to IGVC about how they are doing ground plane segmentation later if that is something you are interested in.
