### ISSUE TITLE
Detect April Tags to Estimate Other Vehicles' Position

### ISSUE THREAD

**Issue by Daniel-Martin576** [RoboJackets/roboracing-software#308]
Really high-level overview:
1. Detect April Tags 
     - http://wiki.ros.org/apriltag_ros
     - https://github.com/AprilRobotics/apriltag_ros
2. Associate Tag with ID for each vehicle
3. Generate hitbox of the opponent car (so that we can dodge it)

Note: Must be able to keep track of multiple cars

EVGP URDF > add Gazebo camera
Add plane with April tag on it > place in the world

**Comment by JasonGibson274** [comment]
Is anyone working on this issue?

**Comment by Daniel-Martin576** [comment]
Replaced with new issues
