### ISSUE TITLE
Steering calculations happen slowly

### ISSUE THREAD

**Issue by evanxq** [RoboJackets/roboracing-software#37]
Items are posted to "/steering" at ~5 Hz on my virtual machine while reading the "circuitfiltered" rosbag.

**Comment by barulicm** [comment]
I believe this is actually an issue with mapper. /map is being published at ~5hz on my machine. The path planner won't plan any faster than the map publishes.
Can you confirm this in your setup? If so, we should shift this issue to focusing on optimizing / improving the mapper.
