### ISSUE TITLE
speedi_controller seems not to interpret /steering correctly

### ISSUE THREAD

**Issue by evanxq** [RoboJackets/roboracing-software#56]
planner publishes a desired steering angle in degrees (-30 to +30 right now), which would be the angle of a central front wheel. The operations applied in speedi_controller to the steering angle make little sense in this context (i.e. tan(pi/2 - steering_angle))

**Comment by barulicm** [comment]
In the development of the simulator, I switched the steering message to use radians instead of degrees, because science.
I tried to change everything over to use radians, but I think that change for the path planner got lost in the simultaneous planner upgrades.
