### ISSUE TITLE
Merge electrical team's e-stop code into the Arduino firmware

### ISSUE THREAD

**Issue by ebretl** [RoboJackets/roboracing-software#67]

**Comment by barulicm** [comment]
This will depend on the final design of the new Joule carrier board. The last design we discussed featured a separate microcontroller for e-stop and RC mux. If the final design keeps two controllers, the e-stop code stays in its own firmware. If they get merged into one, we'll have to make some bigger changes to the current firmware. It currently hangs on serial reads until a new control message pops up.The new firmware will have to be smarter about knowing when its under manual RC control or under computer control.

**Comment by barulicm** [comment]
This is now being moved to the firmware repo.
