### ISSUE TITLE
Create new simulated worlds in gazebo

### ISSUE THREAD

**Issue by chsahit** [RoboJackets/roboracing-software#69]
Including the figure 8 for Speed Demons

**Comment by barulicm** [comment]
- [ ] AVC Speed Demons track
- [ ] AVC Autonomous Car Wars track
- [ ] IARRC circuit track w/ shortcut path

**Comment by barulicm** [comment]
Simulator worlds for our competitions now exist. As there are separate issues for improving them in specific ways, I'm closing this issue.
