### ISSUE TITLE
Planner is slow

### ISSUE THREAD

**Issue by ebretl** [RoboJackets/roboracing-software#71]
When not many paths are eliminated by obstacles (like in the iarrc drag race), the planner uses a full core of my computer at 2.3GHz, even though Gazebo is simulating at less than 0.5 real-time factor. It wasn't doing this as badly before adding the clustering step.

- [ ] Time various steps of planner's computation on AVC course
- [ ] Run same test on IARRC drag course
- [ ] Decrease CPU usage of this node to a reasonable level

**Comment by barulicm** [comment]
Latest planner improvements make it fast enough to run on the Joule, so I think that's good enough for now. See #81 for said improvements.
