### ISSUE TITLE
Add Traffic Light to Simulator

### ISSUE THREAD

**Issue by barulicm** [RoboJackets/roboracing-software#73]
IARRC uses a traffic light to control the start of the race. It would be cool to have this in the simulator for the sake of simulator completeness.

Some ideas about how to make a Gazebo model that can change colors can be found here:
http://answers.gazebosim.org/question/8951/changing-color-of-model-in-gazebo-via-modelplugin/

**Comment by Daniel-Martin576** [comment]
Updated Issue #278 created for this.
