### ISSUE TITLE
Missing Resource - Stop Sign Model

### ISSUE THREAD

**Issue by chsahit** [RoboJackets/roboracing-software#74]
trying to render avc.world requires the stop sign model which is not in the rr_gazebo/models directory

**Comment by barulicm** [comment]
The stop sign model is actually a default model that is available in the gazebo shared model server. I need to look into automatically pulling this model from that server.

**Comment by ebretl** [comment]
I think this issue is fixed

**Comment by barulicm** [comment]
@ebretl By what? @chsahit and I have not found a solution to the problem beyond manually downloading the model in Gazebo and reloading the world.
