### ISSUE TITLE
iarrc color detector does not sense colors accurately in gazebo

### ISSUE THREAD

**Issue by ebretl** [RoboJackets/roboracing-software#80]

**Comment by ebretl** [comment]
![line_detection](https://user-images.githubusercontent.com/15553628/27584746-6c69a0ac-5b39-11e7-83fc-0b6b9dfeed1f.png)

**Comment by ebretl** [comment]
It is also a bit too zealous with finding white lines, as this pic from the drag race track shows

![dragrace_colors](https://user-images.githubusercontent.com/15553628/27585464-a6913af8-5b3c-11e7-8c81-efb8d27d8457.png)

**Comment by barulicm** [comment]
The color detector is using the same rules as were tuned at last year's competition. 
We can tune it for the simulator if we want to, but the current plan is to tune it for real life again when the car is ready.
Also, the last screenshot you're showing isn't finding any white lines, its flagging lots of noise as blue. There are several reasons for this:
1. The old rules for white were based on RGB. We've switched everything to HSV, but haven't implemented the new white rule yet.
2. The old color detector code ran an erosion procedure to get rid of speckly noise. Each color was processed independently though, so we've left this step out until we can try to find a good middle ground for all colors with real-world testing.

The thing I'm most worried about in the image above, however is the fact that it's completely missing the orange cones.

**Comment by ebretl** [comment]
mostly fixed by #82
