### ISSUE TITLE
cluster possible paths using something other than DBSCAN

### ISSUE THREAD

**Issue by ebretl** [RoboJackets/roboracing-software#87]
DBSCAN is the wrong algo for clustering groups of similar paths. We don't have noise in the data; the density doesn't matter, only the cost does; and it needs to be faster. Not the most important problem right now, but it should be fixed.
1. consider aggregating path results into a discrete grid for O(1) neighbors lookup. (Perhaps also take exactly one path sample per grid space.) FLANN KNN is cool, but maybe it solves a harder problem than we need.
2. consider finding clusters by analyzing the distances between local maxima (instead of grouping valid paths through nearest neighbor searches)

**Comment by barulicm** [comment]
I don't remember if we've talked about this before, but would something akin to non-maximal suppression help here?

**Comment by ebretl** [comment]
The current version already thresholds by removing paths that are not within a certain proportion of the best one. Does that count as NMS?

**Comment by barulicm** [comment]
So in vision algorithms, NMS is used to solve this style of problem where you've got "blurry" answers and are trying to reduce them to single points. So, if our threshold is producing islands of good paths, NMS would be able to give us one control vector for each island.

**Comment by ebretl** [comment]
Is this done by repeatedly eroding each island, or by choosing the maximum value from each?

**Comment by barulicm** [comment]
The latter

**Comment by ebretl** [comment]
Cool. Unfortunately our islands are not the result of gaussian blurs/noise, and they sometimes have multiple peaks per "island". It is usually safe to ignore the lower peaks, but I sometimes run into issues where significantly different path decisions make it into the same island. It is hard to tune the filter threshold to deal with this because the required threshold for the edges of path groups is not very consistent in different environments.

**Comment by barulicm** [comment]
What is the dimensionality of our control vectors at this point? Is it still two-stage steering and is velocity factored in at this point in the algorithm?

**Comment by ebretl** [comment]
2D right now with velocity factored (perhaps too strongly) into the cost

**Comment by barulicm** [comment]
It would be cool to plot the cost function to get a sense of its sparseness and the kinds of features we see in it

**Comment by ebretl** [comment]
I have a node for that in the repo

**Comment by ebretl** [comment]
It's a Python script

**Comment by barulicm** [comment]
Awesome

**Comment by ebretl** [comment]
Yeah run planner_plotter.py in rr_common

**Comment by ebretl** [comment]
NB I think something has to be uncommented from the planner.cpp so that steering samples and costs are published

**Comment by ebretl** [comment]
Just had really good success with a partial rewrite of the planner. I switched the clustering algo to finding local minima of costs, and now it keeps up with the lidar's 15hz quite easily

**Comment by barulicm** [comment]
That's awesome! Is this clustering algorithm to the point where we could tell it which branch to choose?
